<?xml version="1.0"?>
<!--
  ZED 2 Stereo Camera for Husky UR3
  Simulated stereo camera for MUSt3R 3D reconstruction
  Assignment 4 Part 2
  
  Supports multiple instances via prefix parameter:
  - Base camera (prefix="zed_base"): Mounted on Husky top plate
  - Arm camera (prefix="zed_arm"): Mounted on UR3 end effector
-->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="zed2_camera" params="prefix parent_link xyz:='0 0 0' rpy:='0 0 0'">

    <!-- ZED 2 Camera Physical Properties -->
    <xacro:property name="baseline" value="0.12" /> <!-- 120mm baseline -->
    <xacro:property name="camera_width" value="0.175" />
    <xacro:property name="camera_height" value="0.040" />  <!-- Increased for visibility -->
    <xacro:property name="camera_depth" value="0.040" />   <!-- Increased for visibility -->
    <xacro:property name="lens_radius" value="0.015" />    <!-- Lens size -->

    <!-- ZED Camera Base Link - Main body -->
    <link name="${prefix}_camera_base_link">
      <visual>
        <geometry>
          <box size="${camera_depth} ${camera_width} ${camera_height}"/>
        </geometry>
        <material name="${prefix}_body_color">
          <color rgba="0.2 0.2 0.2 1.0"/>  <!-- Dark gray body -->
        </material>
      </visual>
      <collision>
        <geometry>
          <box size="${camera_depth} ${camera_width} ${camera_height}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.159"/> <!-- ZED 2 weight: 159g -->
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                 iyy="0.0001" iyz="0.0"
                 izz="0.0001"/>
      </inertial>
    </link>

    <!-- Gazebo material for camera body -->
    <gazebo reference="${prefix}_camera_base_link">
      <material>Gazebo/DarkGrey</material>
    </gazebo>

    <!-- Mount camera to parent -->
    <joint name="${prefix}_camera_joint" type="fixed">
      <parent link="${parent_link}"/>
      <child link="${prefix}_camera_base_link"/>
      <origin xyz="${xyz}" rpy="${rpy}"/>
    </joint>

    <!-- ============================================================ -->
    <!-- Left Camera with visible lens                                -->
    <!-- ============================================================ -->
    
    <link name="${prefix}_left_camera_frame">
      <!-- Visible lens cylinder -->
      <visual>
        <origin xyz="${camera_depth/2 + 0.005} 0 0" rpy="0 ${pi/2} 0"/>
        <geometry>
          <cylinder radius="${lens_radius}" length="0.01"/>
        </geometry>
        <material name="${prefix}_lens_blue">
          <color rgba="0.0 0.5 1.0 1.0"/>  <!-- Blue lens for left -->
        </material>
      </visual>
    </link>
    
    <joint name="${prefix}_left_camera_joint" type="fixed">
      <parent link="${prefix}_camera_base_link"/>
      <child link="${prefix}_left_camera_frame"/>
      <origin xyz="0 ${baseline/2} 0" rpy="0 0 0"/>
    </joint>

    <!-- Gazebo material for left lens -->
    <gazebo reference="${prefix}_left_camera_frame">
      <material>Gazebo/Blue</material>
    </gazebo>

    <!-- Left Camera Optical Frame (standard ROS camera convention) -->
    <link name="${prefix}_left_camera_optical_frame"/>
    <joint name="${prefix}_left_camera_optical_joint" type="fixed">
      <parent link="${prefix}_left_camera_frame"/>
      <child link="${prefix}_left_camera_optical_frame"/>
      <!-- Rotate to optical frame: x=right, y=down, z=forward -->
      <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
    </joint>

    <!-- ============================================================ -->
    <!-- Right Camera with visible lens                               -->
    <!-- ============================================================ -->
    
    <link name="${prefix}_right_camera_frame">
      <!-- Visible lens cylinder -->
      <visual>
        <origin xyz="${camera_depth/2 + 0.005} 0 0" rpy="0 ${pi/2} 0"/>
        <geometry>
          <cylinder radius="${lens_radius}" length="0.01"/>
        </geometry>
        <material name="${prefix}_lens_red">
          <color rgba="1.0 0.3 0.0 1.0"/>  <!-- Orange/red lens for right -->
        </material>
      </visual>
    </link>
    
    <joint name="${prefix}_right_camera_joint" type="fixed">
      <parent link="${prefix}_camera_base_link"/>
      <child link="${prefix}_right_camera_frame"/>
      <origin xyz="0 ${-baseline/2} 0" rpy="0 0 0"/>
    </joint>

    <!-- Gazebo material for right lens -->
    <gazebo reference="${prefix}_right_camera_frame">
      <material>Gazebo/Orange</material>
    </gazebo>

    <!-- Right Camera Optical Frame -->
    <link name="${prefix}_right_camera_optical_frame"/>
    <joint name="${prefix}_right_camera_optical_joint" type="fixed">
      <parent link="${prefix}_right_camera_frame"/>
      <child link="${prefix}_right_camera_optical_frame"/>
      <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
    </joint>

    <!-- ============================================================ -->
    <!-- Gazebo Camera Sensors                                        -->
    <!-- ============================================================ -->

    <!-- Gazebo: Left Camera Sensor -->
    <gazebo reference="${prefix}_left_camera_frame">
      <sensor name="${prefix}_left_camera" type="camera">
        <always_on>1</always_on>
        <update_rate>15.0</update_rate>
        <visualize>true</visualize>
        <topic>${prefix}/left/image_raw</topic>
        <camera name="${prefix}_left">
          <horizontal_fov>1.91986</horizontal_fov>
          <image>
            <width>1280</width>
            <height>720</height>
            <format>RGB_INT8</format>
          </image>
          <clip>
            <near>0.3</near>
            <far>20.0</far>
          </clip>
          <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.007</stddev>
          </noise>
        </camera>
      </sensor>
    </gazebo>

    <!-- Gazebo: Right Camera Sensor -->
    <gazebo reference="${prefix}_right_camera_frame">
      <sensor name="${prefix}_right_camera" type="camera">
        <always_on>1</always_on>
        <update_rate>15.0</update_rate>
        <visualize>true</visualize>
        <topic>${prefix}/right/image_raw</topic>
        <camera name="${prefix}_right">
          <horizontal_fov>1.91986</horizontal_fov>
          <image>
            <width>1280</width>
            <height>720</height>
            <format>RGB_INT8</format>
          </image>
          <clip>
            <near>0.3</near>
            <far>20.0</far>
          </clip>
          <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.007</stddev>
          </noise>
        </camera>
      </sensor>
    </gazebo>

    <!-- Gazebo: Camera Info Publisher -->
    <gazebo>
      <plugin filename="libignition-gazebo-camera-info-system.so" name="ignition::gazebo::systems::CameraInfo">
        <camera_name>${prefix}_left</camera_name>
        <topic>${prefix}/left/camera_info</topic>
        <frame_name>${prefix}_left_camera_optical_frame</frame_name>
      </plugin>
      <plugin filename="libignition-gazebo-camera-info-system.so" name="ignition::gazebo::systems::CameraInfo">
        <camera_name>${prefix}_right</camera_name>
        <topic>${prefix}/right/camera_info</topic>
        <frame_name>${prefix}_right_camera_optical_frame</frame_name>
      </plugin>
    </gazebo>

  </xacro:macro>

</robot>
